import shareClient from './share-client.js?raw';
export const SHARE_HTML = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0b1020"><title>Live Captions</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#edf3ff;font-family:system-ui,-apple-system,sans-serif}button,select,input{font:inherit}button,select{min-height:44px;border:1px solid #43506a;border-radius:12px;background:#172238;color:#edf3ff;padding:8px 12px}button:focus-visible,select:focus-visible,input:focus-visible{outline:3px solid #72b8ff;outline-offset:3px}#wrap{height:100vh;height:100dvh;display:flex;flex-direction:column;padding-top:env(safe-area-inset-top)}header{padding:12px max(16px,env(safe-area-inset-right)) 10px max(16px,env(safe-area-inset-left));background:#10192b;border-bottom:1px solid #26334a}#connection{display:flex;align-items:center;gap:8px;font-size:13px;color:#b5c6df;margin-bottom:10px}.dot{width:8px;height:8px;border-radius:50%;background:#eab65b}.dot.on{background:#5fe0b2}.dot.off{background:#f58a98}#controls{display:flex;flex-wrap:wrap;align-items:center;gap:8px}#language-picker{flex:1;min-width:140px;max-width:100%}#original-toggle{display:flex;align-items:center;gap:8px;min-height:44px;font-size:14px;color:#c5d3e8}input{width:20px;height:20px;accent-color:#7bb6ff}#font-size{min-width:65px}#feed{flex:1;min-height:0;overflow:auto;overflow-anchor:none;padding:20px max(16px,env(safe-area-inset-right)) max(24px,env(safe-area-inset-bottom)) max(16px,env(safe-area-inset-left));scrollbar-gutter:stable}.entry{padding:0 0 20px;margin:0 0 20px;border-bottom:1px solid #25314a}.line{margin-top:12px}.tag{display:block;font-size:12px;letter-spacing:.04em;color:#9cbfff;margin-bottom:5px}.txt{display:block;white-space:pre-wrap;overflow-wrap:anywhere;font-size:var(--caption-size,22px);line-height:1.5;font-weight:550}.orig .txt{font-size:calc(var(--caption-size,22px)*.82);color:#bccae0;font-weight:400}.live{border-left:3px solid #5fe0b2;padding-left:12px}.placeholder{color:#bccae0;font-size:16px;padding:24px 4px}#return-live{position:fixed;bottom:max(18px,env(safe-area-inset-bottom));left:50%;transform:translateX(-50%);background:#c6ddff;color:#10213c;box-shadow:0 4px 24px #0008;white-space:nowrap}#ended{padding:16px;background:#241c2b;color:#ffd0d7;font-size:14px}.hidden{display:none!important}html[data-motion="true"] #return-live{animation:appear .16s ease-out}@keyframes appear{from{opacity:0}to{opacity:1}}@media(prefers-reduced-motion:reduce){*{animation:none!important;scroll-behavior:auto!important}}@media(min-width:700px){#feed{padding-left:max(24px,calc((100% - 760px)/2));padding-right:max(24px,calc((100% - 760px)/2))}}@media(max-height:450px){header{padding-top:6px;padding-bottom:6px}#connection{margin-bottom:4px}}
</style></head><body><div id="wrap"><header>
<div id="connection" role="status" aria-live="polite"><span id="dot" class="dot" aria-hidden="true"></span><span id="status"></span></div>
<div id="controls"><select id="language-picker" aria-label="Translation language"></select><select id="font-size" aria-label="Text size"><option value="18">A−</option><option value="22">A</option><option value="26">A+</option></select><label id="original-toggle"><input id="show-original" type="checkbox"><span id="original-label"></span></label></div>
</header><div id="ended" class="hidden" role="status"><span id="endedText"></span></div><main id="feed" tabindex="0"></main></div>
<button id="return-live" class="hidden" type="button"></button>
<script>${shareClient.replace(/<\/script/gi, '<\\/script')}</script></body></html>`;
